### ISSUE TITLE
User email is not being fetched from the API

### ISSUE THREAD

**Issue by kytrinyx** [ossfriday/ossfriday#67]
When we authorize the user, we're sending the `user:email` scope.

I expected to get the user's email back if it's public, but for my user I didn't get an email.

/cc @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
Not sure what's going on here I'm afraid. I can get the email for my user. Given we're not using the email particularly internally anyway I guess we could just drop the column altogether.

**Comment by kytrinyx** [comment]
> Given we're not using the email particularly internally anyway I guess we could just drop the column altogether.

We're using it to prepopulate the newsletter field.

**Comment by jbjonesjr** [comment]
i did some research into this a while ago, and i think this is a privacy thing we are doing. Even though we have permissions for this via our Privacy Policy, we don't make it available because #values.

If I come across the issue, i'll link it here, but someone from api/platform should be able to fill in the real details.

**Comment by kytrinyx** [comment]
@jbjonesjr the strange thing here is that it's my _own_ email. I'm authenticated with an access_token at this point. At least I thought so.

**Comment by jbjonesjr** [comment]
@kytrinyx is your email public?

**Comment by kytrinyx** [comment]
@jbjonesjr Yepp

**Comment by MikeMcQuaid** [comment]
Removed the email entirely in https://github.com/ossfriday/ossfriday/pull/74
